version: 2

project_name: password-manager

before:
  hooks:
    - go mod tidy
    - go generate ./...

release:
  prerelease: false

builds:
  - id: osx
    binary: pm
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    flags:
      - -trimpath
    env:
      - CGO_ENABLED=1
    ldflags:
      - -s -w -X github.com/nicola-strappazzon/password-manager/cli/version.VERSION=v{{.Version}}

homebrew_casks:
  - name: password-manager
    binaries:
      - pm
    repository:
      owner: nicola-strappazzon
      name: homebrew-tap
      token: "{{ .Env.GITHUB_TOKEN }}"
    homepage: https://github.com/nicola-strappazzon/password-manager
    description: "password-manager is another Unix-style password manager written in Go."
    license: GPL
    completions:
      bash: completions/pm.bash

archives:
  - formats: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    files:
      - completions/*

checksum:
  name_template: "checksums.sha256"

snapshot:
  version_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
